name: Add Notion Habits

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    # API token and database / page IDs for scripts
    environment: notion
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

    steps:
      # Get current day of week
      - name: Current day of week
        id: day_of_week
        run: echo "day_of_week=$(date +'%A')" >> $GITHUB_OUTPUT

      # Get current day of the month
      - name: Current day of the month
        id: day_of_month
        run: echo "day_of_month=$(date +'%d')" >> $GITHUB_OUTPUT
      
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install Pipenv
      - name: Install pipenv
        run: pip install pipenv

      # Install dependencies using Pipenv
      - name: Install dependencies
        run: pipenv install

      # Run the script to add daily habit
      - name: Run daily script each day
        run: pipenv run python run.py --type daily

      # Run the weekly script if it's Monday
      - name: Run weekly script on Monday
        if: ${{ steps.day_of_week.outputs.day_of_week == 'Monday' }}
        run: pipenv run python run.py --type weekly
  
      # Run the monthly script if it's the first day of the month
      - name: Run monthly script on the first day of the month
        if: ${{ steps.day_of_month.outputs.day_of_month == '01' }}
        run: pipenv run python run.py --type monthly
